#!/usr/bin/env python3
"""Grid search for calibration hyperparameters.

This script edits src/calib_config.h with various parameter combinations,
builds the project, runs the calibration and quantized tests, parses mAP,
and records the best parameters in tools/best_params.txt.

Usage:
  python3 tools/grid_search.py [--dry-run]

Set --dry-run to only write files and show the commands without executing them.
"""
import itertools
import subprocess
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CALIB_HEADER = ROOT / "src" / "calib_config.h"
BEST_FILE = ROOT / "tools" / "best_params.txt"
LOG_FILE = ROOT / "tools" / "grid_search_log.txt"

dry = "--dry-run" in sys.argv

# Parameter options
bins_list = [512, 1024, 2048, 4096]
percentiles = [0.998, 0.999, 0.9995]
alphas = [0.05, 0.1, 0.2]

# build candidate list and limit to ~20 combos
combos = list(itertools.product(bins_list, percentiles, alphas))
best_map = -1.0
best_params = None

def write_header(bins, perc, alpha):
    s = f"""// Auto-generated by tools/grid_search.py
#ifndef CALIB_CONFIG_H
#define CALIB_CONFIG_H
#define CALIB_NUM_BINS {bins}
#define CALIB_PERCENTILE {perc}f
#define CALIB_EMA_ALPHA {alpha}f
#define QUANT_MAX_VAL 127.0f
#define TOTAL_CALIB_LAYER 11
#endif
"""
    CALIB_HEADER.write_text(s)

def run_cmd(cmd, cwd=ROOT):
    print("RUN:", " ".join(cmd))
    if dry:
        return ""
    p = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    if p.returncode != 0:
        print("ERROR: command failed:", p.stdout + p.stderr)
        sys.exit(1)
    return p.stdout + p.stderr

def parse_map(output):
    # Look for 'mean average precision' or 'mAP ='
    m = re.search(r"mean average precision.*?([0-9]+\.[0-9]+)", output, re.IGNORECASE)
    if m:
        return float(m.group(1))
    m = re.search(r"mAP\s*=\s*([0-9]+\.[0-9]+)", output, re.IGNORECASE)
    if m:
        return float(m.group(1))
    return None

for bins, perc, alpha in combos:
    print(f"\n===== Testing bins={bins}, perc={perc}, alpha={alpha} =====")

    write_header(bins, perc, alpha)

    run_cmd(["make", "clean"], cwd="/app")
    run_cmd(["make", "-j"], cwd="/app")

    APP_BIN = ROOT / "bin"
    run_cmd(["/bin/sh", "script-unix-aix2024-test-all.sh"], cwd=APP_BIN)
    output = run_cmd(["/bin/sh", "script-unix-aix2024-test-all-quantized.sh"], cwd=APP_BIN)

    mAP = parse_map(output)
    if mAP is None:
        print("ERROR: mAP parsing failed")
        sys.exit(1)

    print("mAP =", mAP)

    with open(LOG_FILE, "a") as f:
        f.write(f"bins={bins} perc={perc} alpha={alpha} mAP={mAP}\n")

    if mAP > best_map:
        best_map = mAP
        best_params = (bins, perc, alpha, mAP)
        with open(BEST_FILE, "w") as bf:
            bf.write(f"best: bins={bins} perc={perc} alpha={alpha} mAP={mAP}\n")

print("DONE. Best:", best_params)
