#!/usr/bin/env python3
"""Grid search for calibration hyperparameters.

This script edits src/calib_config.h with various parameter combinations,
builds the project, runs the calibration and quantized tests, parses mAP,
and records the best parameters in tools/best_params.txt.

Usage:
  python3 tools/grid_search.py [--dry-run]

Set --dry-run to only write files and show the commands without executing them.
"""
import itertools
import subprocess
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CALIB_HEADER = ROOT / "src" / "calib_config.h"
BEST_FILE = ROOT / "tools" / "best_params.txt"
LOG_FILE = ROOT / "tools" / "grid_search_log.txt"

dry = "--dry-run" in sys.argv

# Parameter options
bins_list = [1024, 2048]
percentiles = [0.999, 0.9995, 0.9999]
alphas = [0.15]
methods = ["minmax", "percentile"]

# build candidate list and limit to ~20 combos
all_combos = []
for method in methods:
    if method == "percentile":
        for b, p, a in itertools.product(bins_list, percentiles, alphas):
            all_combos.append((method, b, p, a))
    else:  # minmax
        for a in alphas:
            all_combos.append((method, None, None, a))
combos = all_combos[:20]
best_map = -1.0
best_params = None

def write_header(method, bins, perc, alpha):
    # method: 'percentile' or 'minmax'
    use_pct = 1 if method == "percentile" else 0
    s = f"""// Auto-generated by tools/grid_search.py
#ifndef CALIB_CONFIG_H
#define CALIB_CONFIG_H
#define CALIB_USE_PERCENTILE {use_pct}
"""
    if use_pct:
        s += f"#define CALIB_NUM_BINS {bins}\n"
        s += f"#define CALIB_PERCENTILE {perc}f\n"
    s += f"#define CALIB_EMA_ALPHA {alpha}f\n"
    s += "#define QUANT_MAX_VAL 127.0f\n"
    s += "#define TOTAL_CALIB_LAYER 25\n"
    s += "#endif\n"
    CALIB_HEADER.write_text(s)

def run_cmd(cmd, cwd=ROOT):
    print("RUN:", " ".join(cmd))
    if dry:
        return ""
    p = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    if p.returncode != 0:
        print("ERROR: command failed:", p.stdout + p.stderr)
        sys.exit(1)
    return p.stdout + p.stderr

def parse_map(output):
    # Look for 'mean average precision' or 'mAP ='
    m = re.search(r"mean average precision.*?([0-9]+\.[0-9]+)", output, re.IGNORECASE)
    if m:
        return float(m.group(1))
    m = re.search(r"mAP\s*=\s*([0-9]+\.[0-9]+)", output, re.IGNORECASE)
    if m:
        return float(m.group(1))
    return None

for item in combos:
    method, bins, perc, alpha = item
    print(f"\n===== Testing method={method} bins={bins} perc={perc} alpha={alpha} =====")

    write_header(method, bins, perc, alpha)
    if dry:
        continue

    run_cmd(["make", "clean"], cwd="/app")
    run_cmd(["make", "-j"], cwd="/app")

    APP_BIN = ROOT / "bin"
    run_cmd(["/bin/sh", "script-unix-aix2024-test-all.sh"], cwd=APP_BIN)
    output = run_cmd(["/bin/sh", "script-unix-aix2024-test-all-quantized.sh"], cwd=APP_BIN)

    mAP = parse_map(output)
    if mAP is None:
        print("ERROR: mAP parsing failed")
        sys.exit(1)

    print("mAP =", mAP)

    with open(LOG_FILE, "a") as f:
        f.write(f"bins={bins} perc={perc} alpha={alpha} mAP={mAP}\n")

    if mAP > best_map:
        best_map = mAP
        best_params = (bins, perc, alpha, mAP)
        with open(BEST_FILE, "w") as bf:
            bf.write(f"best: bins={bins} perc={perc} alpha={alpha} mAP={mAP}\n")

print("DONE. Best:", best_params)
