// Auto-generated by tools/grid_search.py
#ifndef CALIB_CONFIG_H
#define CALIB_CONFIG_H
#define CALIB_USE_PERCENTILE 1
#define CALIB_NUM_BINS 2048
#define CALIB_PERCENTILE 0.9999f
#define CALIB_EMA_ALPHA 0.15f
#define QUANT_MAX_VAL 127.0f
#define TOTAL_CALIB_LAYER 25
#endif
