// Auto-generated by tools/grid_search.py
#ifndef CALIB_CONFIG_H
#define CALIB_CONFIG_H
#define CALIB_NUM_BINS 512
#define CALIB_PERCENTILE 0.998f
#define CALIB_EMA_ALPHA 0.2f
#define QUANT_MAX_VAL 127.0f
#define TOTAL_CALIB_LAYER 11
#endif
